name: Deploy Laravel to cPanel via FTP

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' 

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader

      - name: Install NPM dependencies and build assets
        run: |
          npm install
          npm run build

      # Step 6: Upload files to cPanel via FTP
      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }} 
          local-dir: ./  
          server-dir: /home/idek3326/repositories/education  
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
        
      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }} 
          local-dir: ./public
          server-dir: /home/idek3326/public_html/education
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

      - name: Clear Laravel cache
        run: |
          curl -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/home/idek3326/repositories/education/artisan config:cache
          curl -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/home/idek3326/repositories/education/artisan route:cache
          curl -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/home/idek3326/repositories/education/artisan view:cache
